### ISSUE TITLE
go-ping: Reachability detection issue

### ISSUE THREAD

**Issue by jasonjoo2010** [projecteru2/core#468]
# Background

Recently, we are integrating with `go-ping` to detect a sort of reachability. And found that Eru also uses this library. But the usage is not right as shown below:

```go
goroutine 118 [running]:
runtime/debug.Stack(0x6, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x25
github.com/go-ping/ping.(*Pinger).listen(0xc00089f080, 0x166db7a, 0x4, 0x3, 0xc000426518, 0x2)
	/Users/hblzxsj/go/pkg/mod/github.com/go-ping/ping@v0.0.0-20210407214646-e4e642a95741/ping.go:733 +0xed
github.com/go-ping/ping.(*Pinger).Run(0xc00089f080, 0x0, 0x0)
	/Users/hblzxsj/go/pkg/mod/github.com/go-ping/ping@v0.0.0-20210407214646-e4e642a95741/ping.go:400 +0x15a
github.com/projecteru2/core/client/utils.(*EndpointPusher).checkReachability(0xc0002f21c0, 0xc0007f0140, 0xd, 0x0, 0x0)
	/Users/hblzxsj/go/pkg/mod/github.com/projecteru2/core@v0.0.0-20210702031802-4ae6409a2524/client/utils/servicepusher.go:128 +0x137
github.com/projecteru2/core/client/utils.(*EndpointPusher).pollReachability(0xc0002f21c0, 0x185bf60, 0xc000330680, 0xc0007f0140, 0x12)
	/Users/hblzxsj/go/pkg/mod/github.com/projecteru2/core@v0.0.0-20210702031802-4ae6409a2524/client/utils/servicepusher.go:106 +0xe5
created by github.com/projecteru2/core/client/utils.(*EndpointPusher).addCheck
	/Users/hblzxsj/go/pkg/mod/github.com/projecteru2/core@v0.0.0-20210702031802-4ae6409a2524/client/utils/servicepusher.go:86 +0x212
```

# Issue

On Unix posix system non-root users can only send ICMP over UDP while the root(wheel) can send another type of ICMP: raw ICMP over IP protocol.
But things are different on Linux. The raw ICMP can be sent by the root which is the same to Unix, but all the users including root are restricted to send ICMP over UDP. More details can be reached on https://github.com/go-ping/ping#linux

# Workaround

There are several workarounds on it. But if we can run it as root, the easiest way is to add `pinger.SetPrivileged(os.Getuid() == 0)` before calling `Run()`.

**Comment by jschwinger233** [comment]
Sure, thanks for reporting.
