### ISSUE TITLE
inplace update failed

### ISSUE THREAD

**Issue by CMGS** [projecteru2/core#94]
```
time="2019-06-20 09:45:02" level=info msg="[rpc] DeployStatus start virtual"
time="2019-06-20 09:45:02" level=info msg="[rpc] DeployStatus start redisproxy"
time="2019-06-20 09:45:02" level=info msg="[rpc] DeployStatus start redissingular"
time="2019-06-20 09:45:02" level=info msg="[rpc] DeployStatus start rediscluster"
time="2019-06-20 09:45:36" level=info msg="[rpc] DeployStatus stop redissingular"
time="2019-06-20 09:45:36" level=info msg="[rpc] DeployStatus stop virtual"
time="2019-06-20 09:45:36" level=info msg="[rpc] DeployStatus stop redisproxy"
time="2019-06-20 09:45:36" level=info msg="[rpc] DeployStatus stop rediscluster"
time="2019-06-20 09:46:28" level=debug msg="[task] ReplaceContainer added"
time="2019-06-20 09:46:28" level=debug msg="[withContainerLocked] Container 5baa5cbb981a154beca2407bbb1d0b7ee1b4e5212e53f273a19e1b50a7ca8b3e locked"
time="2019-06-20 09:46:28" level=warning msg="[ReplaceContainer] Skip not in pod container 5baa5cbb981a154beca2407bbb1d0b7ee1b4e5212e53f273a19e1b50a7ca8b3e"
time="2019-06-20 09:46:28" level=debug msg="[doUnlock] Unlock 5baa5cbb981a154beca2407bbb1d0b7ee1b4e5212e53f273a19e1b50a7ca8b3e"
time="2019-06-20 09:46:28" level=error msg="[ReplaceContainer] Replace and remove failed Not Support: container 5baa5cbb981a154beca2407bbb1d0b7ee1b4e5212e53f273a19e1b50a7ca8b3e not in pod slave, old container restarted"
time="2019-06-20 09:46:28" level=debug msg="[task] ReplaceContainer done"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xda3e6b]
goroutine 2568 [running]:
github.com/projecteru2/core/rpc.toRPCRemoveContainerMessage(...)
	/go/src/github.com/projecteru2/core/rpc/transform.go:325
github.com/projecteru2/core/rpc.toRPCReplaceContainerMessage(0xc000440560, 0xc000993c58)
	/go/src/github.com/projecteru2/core/rpc/transform.go:278 +0x4b
github.com/projecteru2/core/rpc.(*Vibranium).ReplaceContainer(0xc0001ea1c0, 0xc000a3ede0, 0x11dc1e0, 0xc000a3a0a0, 0x0, 0x0)
	/go/src/github.com/projecteru2/core/rpc/rpc.go:509 +0x1a1
github.com/projecteru2/core/rpc/gen._CoreRPC_ReplaceContainer_Handler(0x1023480, 0xc0001ea1c0, 0x11da680, 0xc0002486c0, 0x1adbfc8, 0xc000163400)
	/go/src/github.com/projecteru2/core/rpc/gen/core.pb.go:4929 +0x10c
github.com/projecteru2/core/vendor/google.golang.org/grpc.(*Server).processStreamingRPC(0xc000514900, 0x11e00e0, 0xc000262300, 0xc000163400, 0xc0003f2000, 0x1a70b20, 0x0, 0x0, 0x0)
	/go/src/github.com/projecteru2/core/vendor/google.golang.org/grpc/server.go:1170 +0xacd
github.com/projecteru2/core/vendor/google.golang.org/grpc.(*Server).handleStream(0xc000514900, 0x11e00e0, 0xc000262300, 0xc000163400, 0x0)
	/go/src/github.com/projecteru2/core/vendor/google.golang.org/grpc/server.go:1249 +0xcbe
github.com/projecteru2/core/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000b3c7b0, 0xc000514900, 0x11e00e0, 0xc000262300, 0xc000163400)
	/go/src/github.com/projecteru2/core/vendor/google.golang.org/grpc/server.go:685 +0x9f
created by github.com/projecteru2/core/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/github.com/projecteru2/core/vendor/google.golang.org/grpc/server.go:683 +0xa1
time="2019-06-20 09:46:29" level=info msg="[main] Cluster started successfully."
```

**Comment by CMGS** [comment]
hotfixed
