### ISSUE TITLE
dissociate issue

### ISSUE THREAD

**Issue by CMGS** [projecteru2/core#95]
time="2019-06-20 10:52:44" level=debug msg="[task] ReplaceContainer done"
time="2019-06-20 10:54:20" level=debug msg="[task] DissociateContainer added"
time="2019-06-20 10:54:20" level=debug msg="[withContainerLocked] Container 8203dfe19ba10d6eebf83905e26bdf66413a4615abaa9a6cb0d67140b244f354 locked"
time="2019-06-20 10:54:20" level=debug msg="[withNodeLocked] Node cachecloud-master-sg2-test-0.shopeemobile.com locked"
time="2019-06-20 10:54:20" level=info msg="[DissociateContainer] Container 8203dfe19ba10d6eebf83905e26bdf66413a4615abaa9a6cb0d67140b244f354 dissociated"
time="2019-06-20 10:54:20" level=debug msg="[Metrics] Update cachecloud-master-sg2-test-0.shopeemobile.com memory capacity gauge"
time="2019-06-20 10:54:20" level=debug msg="[UpdateNode] pod admin node cachecloud-master-sg2-test-0.shopeemobile.com cpu slots map[0:100 1:100 10:100 11:100 12:100 13:100 14:100 15:100 16:100 17:100 18:100 19:100 2:100 20:100 21:100 22:100 23:100 24:100 25:100 26:100 27:100 28:100 29:100 3:100 30:100 31:100 32:100 33:100 34:100 35:100 36:100 37:100 38:100 39:100 4:100 40:100 41:100 42:100 43:100 44:100 45:100 46:100 47:100 5:100 6:100 7:100 8:100 9:100] memory 131345006592"
time="2019-06-20 10:54:20" level=debug msg="[doUnlock] Unlock cachecloud-master-sg2-test-0.shopeemobile.com"
time="2019-06-20 10:54:20" level=debug msg="[doUnlock] Unlock 8203dfe19ba10d6eebf83905e26bdf66413a4615abaa9a6cb0d67140b244f354"
time="2019-06-20 10:54:20" level=debug msg="[task] DissociateContainer done"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xda0aac]
goroutine 1719 [running]:
github.com/projecteru2/core/rpc.toRPCDissociateContainerMessage(...)
	/go/src/github.com/projecteru2/core/rpc/transform.go:335
github.com/projecteru2/core/rpc.(*Vibranium).DissociateContainer(0xc0001f01c0, 0xc0008f5400, 0x11dc000, 0xc000c0bed0, 0x0, 0x0)
	/go/src/github.com/projecteru2/core/rpc/rpc.go:566 +0x19c
github.com/projecteru2/core/rpc/gen._CoreRPC_DissociateContainer_Handler(0x1023480, 0xc0001f01c0, 0x11da620, 0xc0009ce0c0, 0x1adbfc8, 0xc0008e0d00)
	/go/src/github.com/projecteru2/core/rpc/gen/core.pb.go:4971 +0x109
github.com/projecteru2/core/vendor/google.golang.org/grpc.(*Server).processStreamingRPC(0xc000532c00, 0x11e0080, 0xc000a66900, 0xc0008e0d00, 0xc0005506f0, 0x1a70b60, 0x0, 0x0, 0x0)
	/go/src/github.com/projecteru2/core/vendor/google.golang.org/grpc/server.go:1170 +0xacd
github.com/projecteru2/core/vendor/google.golang.org/grpc.(*Server).handleStream(0xc000532c00, 0x11e0080, 0xc000a66900, 0xc0008e0d00, 0x0)
	/go/src/github.com/projecteru2/core/vendor/google.golang.org/grpc/server.go:1249 +0xcbe
github.com/projecteru2/core/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0009b4100, 0xc000532c00, 0x11e0080, 0xc000a66900, 0xc0008e0d00)
	/go/src/github.com/projecteru2/core/vendor/google.golang.org/grpc/server.go:685 +0x9f
created by github.com/projecteru2/core/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/github.com/projecteru2/core/vendor/google.golang.org/grpc/server.go:683 +0xa1

**Comment by CMGS** [comment]
hotfixed
